$order: 1
$title@: Product Management
$title@: Gestion de producto

description@: Our second step is user experience, we will make flow for main cases and try on real users
description@: Nuestro segundo paso es la experiencia del usuario, haremos un flujo para los casos principales y probaremos usuarios reales
icon: /static/images/icons/triangle.svg